$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: poetry-env
description: Environment with PyTorch and required libraries
build:
  path: .
  dockerfile_path: Dockerfile